src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $comment = null;

    #[ORM\Column]
    private ?int $rate = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Episode $Episode = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $Author = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getEpisode(): ?Episode
    {
        return $this->Episode;
    }

    public function setEpisode(?Episode $Episode): self
    {
        $this->Episode = $Episode;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Entity/Program.php
<?php

namespace App\Entity;

use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Category;
use App\Entity\Episode;
use App\Entity\Season;
use App\Entity\Actor;
use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Type;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: ProgramRepository::class)]
#[UniqueEntity('title', message: "ce titre existe déjà")]
#[Vich\Uploadable]
class Program
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name: 'title', type: 'string', length: 255, unique: true)]
    #[Assert\NotBlank(message: 'Ne me laisse pas tout vide')]
    #[Assert\Length(max: 255, maxMessage: 'La catégorie saisie {{ value }} est trop longue, elle ne devrait pas dépasser {{ limit }} caractères',)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: 'Ne me laisse pas tout vide')]
    #[Assert\NotEqualTo('plus belle la vie', message: "On parle de vraies séries ici")]
    private ?string $synopsis = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poster = null;

    #[Vich\UploadableField(mapping: 'poster_file', fileNameProperty: 'poster')]
    #[Assert\File(
        maxSize: '1M',
        mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    )]
    private ?File $posterFile = null;

    #[ORM\ManyToOne(inversedBy: 'programs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?category $category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(nullable: true)]
    private ?int $year = null;

    #[ORM\OneToMany(mappedBy: 'program', targetEntity: Season::class, orphanRemoval: true)]
    private Collection $seasons;

    #[ORM\ManyToMany(targetEntity: Actor::class, mappedBy: 'programs')]
    private Collection $actors;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DatetimeInterface $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'programs')]
    private ?User $owner = null;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUpdatedAt(): ?string
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    /**
     * @return Collection<int, Season>
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons->add($season);
            $season->setProgram($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->removeElement($season)) {
            // set the owning side to null (unless already changed)
            if ($season->getProgram() === $this) {
                $season->setProgram(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Actor>
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors->add($actor);
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeProgram($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
    public function setPosterFile(File $image = null): Program
    {
        $this->posterFile = $image;
        if ($image) {
          $this->updatedAt = new DateTime('now');
        }

        $this->posterFile = $image;
        return $this;
    }

    public function getPosterFile(): ?File
    {
        return $this->posterFile;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Form/ProgramType.php
<?php

namespace App\Form;

use App\Entity\Actor;
use App\Repository\ActorRepository;
use App\Entity\Program;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Vich\UploaderBundle\Form\Type\VichFileType;

class ProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('synopsis', TextType::class)
            ->add('country', TextType::class)
            ->add('year',)
            ->add('category', null, ['choice_label' => 'name']);

        $builder
            ->add('title')
            // ...
            ->add('posterFile', VichFileType::class, [
                'required'      => false,
                'allow_delete'  => true, // not mandatory, default is true
                'download_uri' => true, // not mandatory, default is true
            ]);

        $builder->add('actors', EntityType::class, [
            'by_reference' => false,
            'class' => Actor::class,
            'query_builder' => function (ActorRepository $er) {
                return $er->createQueryBuilder('a')
                    ->orderBy('a.name', 'ASC');
            },
            'choice_label' => 'name',
            'multiple' => true,
            'expanded' => true
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php
// src/Controller/ProgramController.php
namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Comments;
use App\Repository\EpisodeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProgramRepository;
use App\Repository\SeasonRepository;
use App\Entity\Program;
use App\Entity\Season;
use App\Entity\Episode;
use Symfony\Component\HttpFoundation\Request;
use App\Form\ProgramType;
use App\Repository\CommentsRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Service\ProgramDuration;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email as MimeEmail;
use App\Form\CommentsType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

#[Route('/program', name: 'program_')]
class ProgramController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ProgramRepository $programRepository, RequestStack $requestStack,): Response
    {
        $programs = $programRepository->findAll();

        $session = $requestStack->getSession();

        if (!$session->has('total')) {
            $session->set('total', 0); // if total doesn’t exist in session, it is initialized.
        }

        $total = $session->get('total');

        return $this->render('program/index.html.twig', [
            'programs' => $programs,
        ]);
    }

    #[Route('/new', name: 'new')]
    public function new(Request $request, MailerInterface $mailer, ProgramRepository $programRepository, SluggerInterface $slugger): Response
    {
        $program = new Program();
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            
            $slug = $slugger->slug($program->getTitle());
            $program->setSlug($slug);

            $program->setOwner($this->getUser());

            $programRepository->save($program, true);

            $email = (new MimeEmail())
                ->from($this->getParameter('mailer_from'))
                ->to('your_email@example.com')
                ->subject('Une nouvelle série vient d\'être publiée !')
                ->html($this->renderView('program/newProgramEmail.html.twig', ['program' => $program]));

            $mailer->send($email);

            $this->addFlash('success', 'The new program has been created');
            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/new.html.twig', [
            'form' => $form,
            'program' => $program,
        ]);
    }
    #[Route('/{slug}/edit', name: 'edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Program $program, ProgramRepository $programRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($this->getUser() !== $program->getOwner()) {
            // If not the owner, throws a 403 Access Denied exception
            throw $this->createAccessDeniedException('Only the owner can edit the program!');
        }

        if ($form->isSubmitted() && $form->isValid()) {

            $slug = $slugger->slug($program->getTitle());
            $program->setSlug($slug);

            $programRepository->save($program, true);
            $this->addFlash('success', 'The new program has been update');
            return $this->redirectToRoute('program_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('program/edit.html.twig', [
            'season' => $program,
            'form' => $form,
        ]);
    }

    #[Route('/show/{slug}', name: 'show')]
    public function show(program $program, ProgramDuration $programDuration): Response
    {
        if (!$program) {
            throw $this->createNotFoundException(
                'No program with this id is not found in program\'s table.'
            );
        }
        return $this->render('program/show.html.twig', [
            'program' => $program,
            'programDuration' => $programDuration->calculate($program),
        ]);
    }

    #[Route('/show/{program}/season/{season}', requirements: ['program' => '\d+', 'season' => '\d+'], methods: ['GET'], name: 'season_show')]
    public function showSeason(program $program, season $season): Response
    {
        return $this->render('program/season_show.html.twig', ['program' => $program, 'season' => $season]);
    }

    #[Route('/show/{program}/season/{season}/episode/{episode}', requirements: ['program' => '\d+', 'season' => '\d+', 'episode' => '\d+'], methods: ['GET'], name: 'episode_show')]
    public function showEpisode(program $program, season $season, episode $episode): Response
    {
        return $this->render('program/episode_show.html.twig', ['program' => $program, 'season' => $season, 'episode' => $episode]);
    }

    #[Route('/show/{program}/season/{season}/episode/{episode}/comment', name: 'app_comments_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_CONTRIBUTOR')]
    public function newComments(CommentsRepository $commentsRepository, program $program, season $season, episode $episode, Request $request): Response
    {
        $comment = new Comments();
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        $comment->setAuthor($this->getUser());

        if ($form->isSubmitted() && $form->isValid()) {
            $commentsRepository->save($comment, true);
            return $this->redirectToRoute('program_episode_show', ['program' => $program->getId(), 'season' => $season->getId(), 'episode' => $episode->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comments/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }
}

templates/program/_form.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/program/edit.html.twig
{% extends 'index.html.twig' %}

{% block title %}Edit program{% endblock %}

{% block body %}
    <h1>Edit program</h1>

    {{ include('program/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('program_index') }}">back to list</a>
{% endblock %}

templates/program/episode_show.html.twig
{% extends 'index.html.twig' %}

{% block title %}Episode
{% endblock %}

{% block body %}
	<main>
		<h1>Episode</h1>
		<h2>nom du programme
			{{ program.title }}</h2>
		<h3>numero de la saison
			{{ season.number }}</h3>

		<table class="table">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ episode.id }}</td>
				</tr>
				<tr>
					<th>Number</th>
					<td>{{ episode.number }}</td>
				</tr>
				<tr>
					<th>Title</th>
					<td>{{ episode.title }}</td>
				</tr>
				<tr>
					<th>Synospis</th>
					<td>{{ episode.synopsis }}</td>
				</tr>
				<tr>
					<th>Duration</th>
					<td>{{ episode.duration}}</td>
				</tr>
			</tbody>
		</table>

		{% if app.user %}
			<a href="{{path('program_app_comments_new',{'program':program.id,'season':season.id, 'episode':episode.id})}}">add a comment</a>
		{% endif %}
		<br>

		{% for comments in episode.comments %}
			<h6>{{ comments.author.email }}</h6>
			<li>{{ comments.rate ~ ' ' ~ comments.comment }}</li>
			{% if is_granted("ROLE_CONTRIBUTOR") %}
				{{ include('comments/_delete_form.html.twig') }}
			{% endif %}
		{% else %}
			Aucune commentaire trouvée.
		{% endfor %}
		<br>
		<a href="{{path('program_season_show',{'program':program.id,'season':season.id})}}">back to saison</a>

	</main>
{% endblock %}

templates/program/index.html.twig
{% extends 'index.html.twig' %}

{% block title %}All programs
{% endblock %}

{% block body %}
	<div class="d-flex flex-column align-items-center">
		<h1>Toutes les séries de la table program :
		</h1>
		<a href="/program/new">ADD</a>
		{% for program in programs %}
			<div>
				<h2>{{ loop.index }}
					/
					{{ program.title }}
				</h2>
				- Catégorie :
				{{ program.category.name }}</h2>
			<p>{{ program.synopsis }}</p>
			<a href="{{ path("program_show", { slug: program.slug }) }}">Voir la fiche</a>
		</div>
	{% else %}
		Aucune série trouvée.
	{% endfor %}

	{{ app.session.get('total') }}

	<a href="{{ path('app_index')}}">Retour à l'accueil</a>
</div>{% endblock %}

templates/program/new.html.twig
{% extends "index.html.twig" %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block body %}
	<main>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit">Add category</button>
    {{ form_end(form) }}
		</main>
	{% endblock %}

templates/program/newProgramEmail.html.twig
{% extends 'Email.html.twig' %}


{% block body %}
	<body>
		<h1>New program
			{{ program.title }}
			created</h1>
		<p>Hello, the new program
			{{ program.title }}
			has been created on Wild Series</p>
		<p>Synopsis :
			{{program.synopsis }}</p>
	</body>
</html>{% endblock %}

templates/program/season_show.html.twig
{% extends 'index.html.twig' %}

{% block title %}Season
{% endblock %}

{% block body %}
	<main>
		<h1>Season</h1>

		<table class="table">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ season.id }}</td>
				</tr>
				<tr>
					<th>Number</th>
					<td>{{ season.number }}</td>
				</tr>
				<tr>
					<th>Year</th>
					<td>{{ season.year }}</td>
				</tr>
				<tr>
					<th>Description</th>
					<td>{{ season.description }}</td>
				</tr>
			</tbody>
		</table>
		<ul>
			{% for episode in season.episodes %}
				<li>{{ episode.number ~ ' ' ~ episode.title ~ ' ' ~ episode.synopsis  }}</li>
				<a href="{{path('program_episode_show',{'program':program.id,'season':season.id, 'episode':episode.id})}}">show Me</a>
			{% else %}
				Aucune episode trouvée.
			{% endfor %}
		</ul>

		<a href="{{ path("program_show", { slug: program.slug }) }}">back to list</a>

	</main>
{% endblock %}

templates/program/show.html.twig
{% extends 'index.html.twig' %}

{% block body %}
	<main>
		<div class="media">
			{% if is_granted("ROLE_ADMIN") %}
				{% if is_granted("ROLE_ADMIN") %}
					<a href="{{ path('program_edit', { 'slug': program.slug} ) }}">Éditer</a>
				{% endif %}
				{%endif%}
				<img class="align-self-start mr-3" src="{{ vich_uploader_asset(program) }}" alt="{{ program.title }} poster">
				<div class="media-body">
					<h1 class="mt-0">{{ program.title }}</h1>
					<p>{{ program.synopsis }}</p>
					<p>Catégorie :
						{{ program.category.name }}</p>
				</div>
				<ul>
					{% for season in program.seasons %}
						<li>
							<a href="{{path('program_season_show',{'program':program.id,'season':season.id})}}">{{ season.number }}</a>
						</li>
					{% endfor %}
				</ul>
			</div>

			<strong>Acteurs :</strong>
			<ul>
				{% for actor in program.actors %}
					<li>
						<a href="{{ path("actor_show", { slug: actor.slug }) }}">{{ actor.name }}</a>
					</li>
				{% else %}
					<li>Aucun acteur pour cette série</li>
				{% endfor %}
			</ul>

			<a href="{{ path('program_index') }}">
				Retour à la liste des programmes
			</a>
		</main>
	{% endblock %}